### PR TITLE
Update dependencies to latest version

### PR DESCRIPTION
**Pull request by mostafa**
I updated all the dependencies to the latest versions and removed the replaced dependency.

@auxten Please let me know if this is not OK and if you based the project on certain dependencies. Then we can pin those dependencies.
Also, I am thinking about various ways to contribute to this project. Please let me know of the next steps or create tickets, so we can talk about various aspects of it.

### CODE REVIEW

**Comment by auxten** [comment]
Hey, thanks for your contribution. 
Currently, the test cases are not very complete and there are some projects that depend on it, so I'd prefer to keep the dependences stable if not critical bugs.

**Comment by mostafa** [comment]
OK, so fixing tests are a priority then?

**Comment by auxten** [comment]
> OK, so fixing tests are a priority then?

yeah, but I also think it's an open question. any idea or contribution is welcome.

**Comment by mostafa** [comment]
I'll possibly fix some of it, whenever I find some time.

**Comment by auxten** [comment]
> > any idea or contribution is welcome.
> 
> I'll possibly fix some of it whenever I find some time.

Great! 👍

**Pull request closed without merging**
